VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.10.2"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "vagrant" => ["localhost"]
    }
    ansible.playbook = "provision.yml"
  end

  config.vm.provision "file", source: "packer.json", destination: "packer.json"

end
